# Generated by Django 5.1.4 on 2025-01-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_heartbeatrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeatrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingupdates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
